# Generated by Django 5.2.2 on 2025-06-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_views'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='publications.publication'),
        ),
    ]
